VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "aclsComponent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'
'Private pComponentItem As Variant
'Private pRequired As Boolean
'Private pComponentFamily As String
'Private pParentID As Integer
'Private pChildID As Integer
'
'
'
'Public Property Let ComponentItem(value As Variant)
'Set pComponentItem = value
'End Property
'Public Property Get ComponentItem() As Variant
'Set ComponentItem = pComponentItem
'End Property
'
'Public Property Let Required(value As Boolean)
'pRequired = value
'End Property
'Public Property Get Required() As Boolean
'Required = pRequired
'End Property
'
'Public Property Let ComponentFamily(value As String)
'pComponentFamily = value
'End Property
'Public Property Get ComponentFamily() As String
'ComponentFamily = pComponentFamily
'End Property
'
'Public Property Let ParentID(value As Integer)
'pParentID = value
'End Property
'Public Property Get ParentID() As Integer
'ParentID = pParentID
'End Property
'
'Public Property Let ChildID(value As Integer)
'pChildID = value
'End Property
'Public Property Get ChildID() As Integer
'ChildID = pChildID
'End Property
'
'
'Public Function GetParent() As aclsItem
'Dim member As aclsItem
'For Each member In CItem
'    If member.ParentID = Me.ChildID Then
'        Set GetParent = member
'        Exit For
'    End If
'Next member
'End Function

