VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "zclsItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'
'Private pItemID As Integer
'
'
'Public Property Let ItemID(value As Integer)
'pItemID = value
'End Property
'Public Property Get ItemID() As Integer
'ItemID = pItemID
'End Property
'
'
'Public Sub ItemInitialize(ItemID As Integer)
'End Sub
'Public Sub BuildItemCollection()
'End Sub
'Public Sub RefreshPreviewWindow()
'End Sub
'Public Sub UpdateGUI()
'End Sub
'Public Sub CheckForRequiredComponents(item As aclsItem)
'End Sub

